import { ProjectCreateDto, ProjectRo } from 'src/app/services/api.generated';

export const createProjectInit: ProjectCreateDto = {
  subject: '',
  institution: '',
  category: 'COMPUTER',
  summary: '',
  budgets: [{ title: '', value: 0 }],
  budgetReason: '',
  projectFirstIdea: '',
  projectMainIdea: '',
  projectGoal: '',
  technicalDescriptions: [],
  projectAdditionalInfo: '',
  timeDescription: '',
  timelines: [],
  imageUrls: [],
};

export const emptyProject: ProjectRo = {
  id: '',
  subject: '',
  institution: '',
  category: 'COMPUTER',
  summary: '',
  budgets: [],
  budgetReason: '',
  projectFirstIdea: '',
  projectMainIdea: '',
  projectGoal: '',
  technicalDescriptions: [],
  projectAdditionalInfo: '',
  timeDescription: '',
  timelines: [],
  imageUrls: [],
  state: 'START',
  totalPayedMoney: 0,
  owner: {
    username: '',
    firstName: '',
    lastName: '',
    email: '',
    roleNames: [],
    avatarAddress: '',
    description: '',
    headline: '',
    address: '',
    website: '',
    linkedinAddress: '',
    mailConfig: {
      profile: true,
      supportedProjects: true,
      createdProjects: true,
      crowdfundingUpdates: true,
      projectReviews: true,
      magazine: true,
    },
  },
  rewards: [],
  reviews: [],
};
